version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: legal_services
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: php_app
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASS=password
      - DB_NAME=legal_services
    volumes:
      - ./public:/var/www/html

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: legal_services
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://root:rootpassword@mongo:27017/legal_services?authSource=admin
    volumes:
      - ./:/app
      - /app/node_modules

volumes:
  mongodb_data:

